version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  start:
    build:
      working_directory: ~/src
      docker:
        - image: cimg/node:lts               # the primary container, where your job's commands are run
      steps:
        - checkout:                              # check out the code in the project directory
          path: ~/src
        - run: npm install               # print 'hello world'
      

#workflows:
#  my-workflow:                                # Name of the workflow. You can additional workflows below.
#    jobs:                                     # The jobs to run as part of this workflow
#      - node/test:
#        version: "16.10"
#        pkg-manager: npm
#      - start                             # Example 'hello world' job.