version: 2.1

jobs:
  start:
    build:
      docker:
        - image: src/dockerfile               # the primary container, where your job's commands are run
      steps:
        - checkout                              # check out the code in the project directory
        - run: echo "Test finished"               # print 'hello world'
      

workflows:
  my-workflow:                                # Name of the workflow. You can additional workflows below.
    jobs:                                     # The jobs to run as part of this workflow
      - start                             # Example 'hello world' job.